### ISSUE TITLE
CALACS (2.0.0rc1 for HSTDP-2018.1) failures on two ACS association datasets

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/hstcal#299]
The FITS keywords using the STScI convention for images represented by a single value cannot be found in the ERR extension header (NPIX1,NPIX2, and PIXVALUE).  This issue was introduced inadvertently as part of the new ACSREJ algorithm.

Core was generated by `calacs.e -tv j8cr50010_asn'.
Program terminated with signal 11, Segmentation fault.
```
#0  0x000000000044acd9 in find (h=0x0, nm=0x7ffc7542cba0 "NPIX1", kw=0x774ea0 <findkw>) at ../hstio/keyword.c:115
115         ../hstio/keyword.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64
(gdb) where
#0  0x000000000044acd9 in find (h=0x0, nm=0x7ffc7542cba0 "NPIX1", kw=0x774ea0 <findkw>) at ../hstio/keyword.c:115
#1  0x000000000044ae59 in findKw (h=0x0, name=<optimized out>) at ../hstio/keyword.c:425
#2  0x0000000000440bf8 in getFloatLine (iodesc_=0xec4d40, line=0, ptr=0x1dc1830) at ../hstio/hstio.c:3261
#3  0x0000000000418393 in acsrej_loop (ipsci=0x7ffc754352e0, iperr=0x7ffc75434f20, ipdq=0x7ffc75434b60, imgname=0x7ffc7542d3d0, grp=0x7ffc754356a0, nimgs=2, par=0x7ffc75436340, niter=3, dim_x=1024,
    dim_y=1024, sigma=0x7ffc75435df0, noise=..., gain=..., efac=0x7ffc75435880, skyval=0x7ffc75435a60, ave=0x7ffc7542d2c0, avevar=0x7ffc7542d310, efacsum=0xfa3860, dq=0x7ffc7542d360,
    nrej=0x7ffc7542d3b8, shadfile=0x7ffc75435c40 "") at ../pkg/acs/calacs/acsrej/acsrej_loop.c:551
```

**Comment by pllim** [comment]
Bad data or bad logic? Does this mean one of the input has blank ERR? Or is it the output? I can't tell from the description. Any bug in that algorithm from #2 is probably my bad, sorry. Thanks for looking into this!
